
server:
  port: 9999
  
spring:
  application:
    name: user-service
    
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/21springboot?serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    
#eureka配置
eureka:
  client:
    service-url:                  # EurekaServer的地址
      defaultZone: http://127.0.0.1:8888/eureka
      