
server:
  port: 10000
  
spring:
  application:
    name: customer	#显示在Eureka中的服务名
    
eureka:
  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false     # 是否拉取其它服务的信息，默认是true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
    
feign:
  client: 
    config: 
      default: 
        connect-timeout: 1000  #设置Feign连接超时时间
        read-timeout: 4000  #设置Feign读取超时时间
  hystrix:
    enabled: true # 开启Feign的熔断功能
    
hystrix:
  command:
    default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000 # 设置hystrix的超时时间为6000ms，默认1000ms